### ISSUE TITLE
Trouble with task.alert.type

### ISSUE THREAD

**Issue by Gnolive** [mislavcimpersak/anydo-widget#1] opened 2015-04-30 14:31 UTC
After entering username and password in the right place, all I get is this error message:
**undefined is not an object (evaluating 'task.alert.type')**
and I'm unable to correct the trouble.

**Comment by mislavcimpersak** [comment] 2015-04-30 14:41
Can you verify that any other ubersicht widget is working?

Could you please take a screenshot and share it here?

**Comment by Gnolive** [comment] 2015-04-30 15:08
I'm also running the sys-mon-set.widget. I've removed it, changed nothing.
The screenshot:
![capture d ecran 2015-04-30 a 16 58 44](https://cloud.githubusercontent.com/assets/12187042/7415814/79e4d1da-ef5b-11e4-921e-12d33712c192.png)

**Comment by mislavcimpersak** [comment] 2015-05-04 08:49
Could you give me more info please?

I cannot reproduce you error :-/ What kind of tasks do you have? I tried recurring tasks, tasks with alerts, notes, attachments. I'm not using premium, so perhaps I'm missing some case.

**Comment by Gnolive** [comment] 2015-05-06 10:32
Hi
Sorry, I wasn't available last days. 
I'm using the free version of any.do. I use alerts, recurring tasks and lists. I do not use notes, attachments, sub-tasks nor sharing. Could it be because I use diacritic marks (e.g. éphémère) in my tasks and lists names ?

**Comment by mislavcimpersak** [comment] 2015-05-07 11:42
Nope, it's not the diacritics (I use Croatian characters with diacritics myself).

I added several test tasks to my any.do. Some that use alerts, some that are recurring and added tasks to three different lists. Still I'm unable to replicate the problem :-/

**Comment by Gnolive** [comment] 2015-05-07 12:50
I've created a test account and it worked flawless. Shit!
May I send you my name/pass so you can see by yourself? I've nothing sensible and l'll change the pass afterwards.

**Comment by mislavcimpersak** [comment] 2015-05-07 13:11
Sure. Send it to `mislav dot cimpersak (at) gmail dot com` :)

**Comment by mislavcimpersak** [comment] 2015-05-13 14:38
@Gnolive: I've made some adjustments. Could you please try now?

**Comment by Gnolive** [comment] 2015-05-13 15:48
Works fine. Great job! Thank you.

Olivier Pellerin

**Comment by mislavcimpersak** [comment] 2015-05-14 07:27
Excellent :)
I'm closing the issue.

**Closed as completed by mislavcimpersak** 2015-05-14 07:27 UTC
